name = "credits"
main = "src/index.ts"
compatibility_date = "2024-04-27"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "credits-db"
database_id = "522e3bc3-d05f-4abe-8478-e8452a44a20a"